name: bulletproof_auth
description: Firebase and Riverpod. Together in (perfect)? harmony
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.23.0 # 2.21.0  # hardcode if you want to use the last known invertase repo in Podfile (10.16)
  cloud_firestore: any
  cloud_functions: any
  firebase_auth: any
  firebase_crashlytics: any

  flutter_riverpod: ^2.4.8
  fpdart: ^1.1.0
  riverpod_annotation: ^2.3.2
  routemaster: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true
