name: bulletproof_auth
description: Firebase and Riverpod. Together in (perfect)? harmony
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.10.1

  flutter_riverpod: ^2.4.3
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  cloud_functions: ^4.5.3

dev_dependencies:
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
